version: "3"
services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 20
  chrome1:
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 10
      NODE_MAX_INSTANCES: 10
      SCREEN_WIDTH: 1526
      SCREEN_HEIGHT: 967
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 2G
    links:
      - hub
  firefox1:
    image: selenium/node-firefox
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 10
      NODE_MAX_INSTANCES: 10
      SCREEN_WIDTH: 1526
      SCREEN_HEIGHT: 967
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 2G
    links:
      - hub
